### ISSUE TITLE
IP Locator / Referrer not working with docker + reverse proxy 

### ISSUE THREAD

**Issue by misterfifi1** [shlinkio/shlink-docker-image#53] opened 2019-07-30 16:46 UTC
Hello, 

Thanks for your application, but I have an issue with the IP forwarding, despite my reverse proxy configuration, the IP is always: 172.17.0.0

The same for the referrer which is aways null.

Could you please help me? 

Regards,

**Comment by acelaya** [comment] 2019-07-31 10:47
Shlink picks the IP address from the usual standard headers. Did you configure your proxy to send the x-fowarded-for header?

**Comment by misterfifi1** [comment] 2019-07-31 21:46
yes, I checked that part, on my gitlab I have the same config and it can get the IP

**Comment by acelaya** [comment] 2019-08-01 04:49
The library I use to detect the address inspects some request headers looking for the IP, but depending on your proxy and how you configured it, it might be using something different.

I have some ideas to improve IP detection, but it would help to know your setup just to make sure.

Can I ask what proxy are you using and how is it configured?

**Comment by acelaya** [comment] 2019-08-01 04:54
This is probably related with this https://github.com/shlinkio/shlink/issues/384

In the last comment I included the list of headers I'm going to inspect in next version.

Currently all but the first three are being inspected.

**Comment by misterfifi1** [comment] 2019-08-01 07:36
Hi, 

it seems to be related, but do you know why the user-agent is working but not the referrer?

Please find below the header that I am forwarding in my VHost
                proxy_set_header  X-Forwarded-For $remote_addr;
                proxy_set_header  X-Forwarded-Host $remote_addr;
                proxy_set_header  X-Real-IP $remote_addr;
                proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header  X-Forwarded-Referrer $http_referer;
                proxy_set_header  Referer $http_referer;


Thanks for tour help

**Comment by acelaya** [comment] 2019-08-01 12:17
I also have a proxy in front of my shlink, and the only difference I see is that I don't have your first line.

Could you try just with this?

```
proxy_set_header X-Forwarded-Host $remote_addr;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Referrer $http_referer;
proxy_set_header Referer $http_referer;
```

**Comment by misterfifi1** [comment] 2019-08-01 18:54
Thanks for your answer! 

unfortunately, it is exactly the same :( 

![image](https://user-images.githubusercontent.com/5573438/62319540-7a3a8a00-b49e-11e9-9c60-8a8f42e18c5c.png)

**Comment by acelaya** [comment] 2019-08-01 19:46
Then I would say the problem is before the proxy. Can you verify the address is correct at the proxy before forwarding the request?

**Comment by acelaya** [comment] 2019-08-11 10:57
I'm closing this for now, since there's not enough information to reproduce it.

**Closed as completed by acelaya** 2019-08-11 10:57 UTC
Labels: question
